#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: get a real certificate and the booth name onto the Pi.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE="${ENV_FILE:-.env}"
CERT_DIR="${CERT_DIR:-$HOME/booth-certs}"

banner "Apple Fest POS: HTTPS on the booth network"


_clear
printf '\n%s%s  Before you start%s\n\n' "$BOLD" "$BLUE" "$RESET"
say "Stages 1 to 4 need the internet only. The certificate comes by DNS-01, so"
say "it never touches the Pi or the router."
say "Stages 5 to 8 need the booth network: the GL.iNet powered on, the Pi joined"
say "to it, and this Mac joined to it."
say ""
say "The short way is one sitting. Put the GL.iNet in Repeater mode against your"
say "home wifi, then the booth network has an uplink and all eight stages run in"
say "a row. At the event you leave the uplink off."
say ""
note "Stop with Ctrl-C at any time. Every value goes to $ENV_FILE, and a re-run"
note "offers it back, so two sittings cost nothing."
pause

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "DuckDNS: the booth name"
say "The booth needs a public name that a Let's Encrypt certificate can cover."
say "DuckDNS gives you one free, and the token proves the name is yours."
open_url "https://www.duckdns.org/"
step "Sign in with any of the listed accounts."
step "Type a subdomain in the 'domains' box and click 'add domain'."
step "Do NOT set an IP address. DNS-01 uses a TXT record only."
step "Copy the token from the top of the page."
ask BOOTH_SUBDOMAIN "The subdomain you added (name only, no .duckdns.org):"
ask_secret DUCKDNS_TOKEN "Paste the DuckDNS token:"
write_env BOOTH_SUBDOMAIN "$BOOTH_SUBDOMAIN"
write_env DUCKDNS_TOKEN "$DUCKDNS_TOKEN"
BOOTH_HOST="pos.${BOOTH_SUBDOMAIN}.duckdns.org"
write_env BOOTH_HOST "$BOOTH_HOST"
note "The booth name is $BOOTH_HOST"
note "$ENV_FILE holds the token and git ignores that file. Keep it off the Pi."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "lego on the Mac"
say "lego is the ACME client. It runs on the Mac only, never on the Pi."
if command -v lego >/dev/null 2>&1; then
  note "lego is already installed: $(lego --version 2>&1 | head -n1)"
else
  if confirm "Install lego with Homebrew now?"; then
    brew install lego
  else
    SKIPPED+=("install lego (brew install lego)")
    warn "without lego the next two stages cannot run"
  fi
fi
say "lego names the DuckDNS credential in its own help. Read it here:"
lego dnshelp -c duckdns 2>&1 | sed 's/^/    /' || warn "lego dnshelp failed"
ask DUCKDNS_ENV_NAME "The credential variable lego printed [DUCKDNS_TOKEN]:"
[[ -z "$DUCKDNS_ENV_NAME" ]] && DUCKDNS_ENV_NAME="DUCKDNS_TOKEN"
write_env DUCKDNS_ENV_NAME "$DUCKDNS_ENV_NAME"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Staging certificate: prove the command"
say "Let's Encrypt limits production certificates hard, so test the command"
say "against the staging server first. A staging certificate is not trusted;"
say "it only proves that the DNS-01 challenge works."
ask ACME_EMAIL "Your email for the ACME account:"
write_env ACME_EMAIL "$ACME_EMAIL"
mkdir -p "$CERT_DIR"
say "Command:"
note "  $DUCKDNS_ENV_NAME=**** lego --accept-tos --email $ACME_EMAIL \\"
note "    --dns duckdns --domains $BOOTH_HOST --path $CERT_DIR \\"
note "    --server https://acme-staging-v02.api.letsencrypt.org/directory run"
if confirm "Run the staging issue now?"; then
  env "$DUCKDNS_ENV_NAME=$DUCKDNS_TOKEN" lego --accept-tos --email "$ACME_EMAIL" \
    --dns duckdns --domains "$BOOTH_HOST" --path "$CERT_DIR" \
    --server https://acme-staging-v02.api.letsencrypt.org/directory run \
    && printf '  %s✓ staging issue worked%s\n' "$GREEN" "$RESET" \
    || warn "staging failed. Fix the token or the name before you go on."
else
  SKIPPED+=("staging certificate run")
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Production certificate"
say "Same command against the real server. This one the tablets will trust."
warn "The certificate lasts 90 days. Note the expiry date; the venue is air-gapped,"
warn "so a renewal must happen at home before the event."
if confirm "Run the production issue now?"; then
  env "$DUCKDNS_ENV_NAME=$DUCKDNS_TOKEN" lego --accept-tos --email "$ACME_EMAIL" \
    --dns duckdns --domains "$BOOTH_HOST" --path "$CERT_DIR" run \
    || warn "production issue failed"
fi
CERT_PATH="$CERT_DIR/certificates/$BOOTH_HOST.crt"
KEY_PATH="$CERT_DIR/certificates/$BOOTH_HOST.key"
if [[ -f "$CERT_PATH" ]]; then
  CERT_EXPIRY=$(openssl x509 -enddate -noout -in "$CERT_PATH" | cut -d= -f2)
  write_env CERT_EXPIRY "$CERT_EXPIRY"
  note "certificate: $CERT_PATH"
  note "key:         $KEY_PATH"
else
  warn "no certificate at $CERT_PATH yet"
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Router: pin the Pi's address"
say "The name must always point at the same address, so pin the Pi first."
open_url "http://192.168.8.1/"
step "Sign in to the GL.iNet AX3000."
step "Go to Clients, find the Pi, and turn on the address reservation."
step "If the Pi is not listed, power it on and join it to the booth network."
ask PI_ADDRESS "The Pi's reserved address (for example 192.168.8.50):"
ask PI_USER "The SSH user on the Pi [pi]:"
[[ -z "$PI_USER" ]] && PI_USER="pi"
write_env PI_ADDRESS "$PI_ADDRESS"
write_env PI_USER "$PI_USER"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Router: point the booth name at the Pi"
say "The name has no public A record, so the router must answer for it."
say "The simple GL.iNet screen may not show static hosts. LuCI always does."
step "GL.iNet 4.x hides LuCI until you turn it on in System → Advanced Settings."
open_url "http://192.168.8.1/cgi-bin/luci/"
step "In LuCI go to Network → DHCP and DNS → Hostnames."
step "Add hostname '$BOOTH_HOST' with address '$PI_ADDRESS' and save and apply."
note "The same thing by hand on the router shell, if you prefer:"
note "  echo \"address=/$BOOTH_HOST/$PI_ADDRESS\" >> /etc/dnsmasq.conf && /etc/init.d/dnsmasq restart"
say "Check it from this Mac, joined to the booth network:"
if confirm "Run the lookup now?"; then
  nslookup "$BOOTH_HOST" 192.168.8.1 || warn "the router did not answer for the name"
fi
warn "Also check it with the router's internet cable unplugged. The event is air-gapped."
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Copy the certificate to the Pi"
say "The certificate and key live in /etc/pos on the Pi, read by the pos user only."
say "The DuckDNS token stays on the Mac. The Pi never runs an ACME client."
if confirm "Copy them to $PI_USER@$PI_ADDRESS now?"; then
  ssh "$PI_USER@$PI_ADDRESS" 'sudo useradd --system --no-create-home pos 2>/dev/null; sudo mkdir -p /etc/pos'
  scp "$CERT_PATH" "$KEY_PATH" "$PI_USER@$PI_ADDRESS:/tmp/"
  ssh "$PI_USER@$PI_ADDRESS" "sudo mv /tmp/$(basename "$CERT_PATH") /etc/pos/pos.crt && \
    sudo mv /tmp/$(basename "$KEY_PATH") /etc/pos/pos.key && \
    sudo chown root:pos /etc/pos/pos.crt /etc/pos/pos.key && \
    sudo chmod 640 /etc/pos/pos.crt /etc/pos/pos.key && ls -l /etc/pos"
else
  SKIPPED+=("copy the certificate to /etc/pos on the Pi")
fi
write_env PI_CERT_PATH "/etc/pos/pos.crt"
write_env PI_KEY_PATH "/etc/pos/pos.key"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Prove it on a real tablet"
say "This stage runs the POS by hand. The systemd unit comes later, in"
say "'Ship one binary to the Pi'."
say "Build and copy the binary, then start it with TLS:"
note "  CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o pos ./cmd/pos"
note "  scp pos $PI_USER@$PI_ADDRESS:/tmp/pos"
note "  ssh $PI_USER@$PI_ADDRESS"
note "  sudo TLS_CERT=/etc/pos/pos.crt TLS_KEY=/etc/pos/pos.key SQLITE_PATH=/tmp/pos-smoke.sqlite /tmp/pos"
say ""
step "On a Pixel tablet joined to the booth network, open https://$BOOTH_HOST"
step "Check the padlock. No warning, no 'Not secure'."
step "Open http://$BOOTH_HOST as well. It must redirect to HTTPS."
step "Put the POS in full screen and check that the screen never sleeps."
note "If the Mac resolves the name but the tablet does not, look at the tablet's"
note "Private DNS setting. A public DoT host bypasses the router. Look only; do"
note "not change device settings."
note "Plain HTTP refuses the Screen Wake Lock, so a screen that stays awake is"
note "the proof that HTTPS did its job."
if confirm "Did the tablet show the padlock and hold the screen awake?"; then
  write_env HTTPS_VERIFIED "yes"
else
  SKIPPED+=("verify the padlock and the wake lock on a Pixel tablet")
fi
pause

finish
say "Report these back to issue #31:"
note "  booth name    $BOOTH_HOST"
note "  Pi address    $PI_ADDRESS"
note "  cert on Pi    /etc/pos/pos.crt and /etc/pos/pos.key"
note "  expires       ${CERT_EXPIRY:-unknown}"
printf '\n'
